### ISSUE TITLE
Enable github.io - make readme links go to rendered notebooks by default

### ISSUE THREAD

**Issue by cgreene** [Sage-Bionetworks/NF_LandscapePaper_2019#22]
In https://github.com/greenelab/multi-plier @jaclyn-taroni used github.io to host the html files. This means that they can be viewed in rendered form when the link on the readme is clicked. I think it's pretty handy. I'd be happy to set this up, but someone with admin on the repo would need to enable github.io first and let me know what the base URL is. 😁

**Comment by cgreene** [comment]
Of course, the fact that it's not setup that way meant that I just cloned the repo so I could more easily view the files, so maybe it's working as intended. 😂

**Comment by allaway** [comment]
That's great, thanks for the suggestion! Up until now I had just used htmlpreview.github.io (and had been meaning to switch the links in the readme to include that), but this seems like a more elegant solution!

**Comment by sgosline** [comment]
@allaway if you accept my PR the html links should work.

**Comment by cgreene** [comment]
Links in the PR don't work b/c they're to github.com instead of .io.
![Screen Shot 2019-10-17 at 11 40 32 AM](https://user-images.githubusercontent.com/542643/67024808-05591280-f0d3-11e9-9b37-9ee0eeba6790.png)

**Comment by allaway** [comment]
I put a comment in the readme for future reference but here's the link structure: https://sage-bionetworks.github.io/NF_LandscapePaper_2019/results/your_html_file.html 

The readme has been edited and all the links should now work. Thanks again for the suggestion!

**Comment by cgreene** [comment]
Tested the first link - confirmed success 👍
