### ISSUE TITLE
redo LV analyses and analyses dependent on this with CHOP pNF data added

### ISSUE THREAD

**Issue by allaway** [Sage-Bionetworks/NF_LandscapePaper_2019#44]

**Comment by allaway** [comment]
@sgosline just to double check, you are referring to this CBTTC data, right?

https://www.synapse.org/#!Synapse:syn20629788/tables/query/eyJzcWwiOiJTRUxFQ1QgKiBGUk9NIHN5bjIwNjI5Nzg4IHdoZXJlIGZpbGVGb3JtYXQgPSAnc2YnIGFuZCB0dW1vclR5cGUgPSAncGxleGlmb3JtIG5ldXJvZmlicm9tYSciLCAiaW5jbHVkZUVudGl0eUV0YWciOnRydWUsICJpc0NvbnNpc3RlbnQiOnRydWUsICJvZmZzZXQiOjAsICJsaW1pdCI6MjV9

**Comment by sgosline** [comment]
Yes! It won't make much fo a difference for the genome variant work, but could help power jineta's random forest.
