### ISSUE TITLE
Add four MPNST samples to Multiplier analysis

### ISSUE THREAD

**Issue by sgosline** [Sage-Bionetworks/NF_LandscapePaper_2019#65]
We have four additional MPNSTs that are not in multiplier.

https://www.synapse.org/#!Synapse:syn21222348/tables/query/eyJzcWwiOiJTRUxFQ1QgZGlzdGluY3QgcGF0aCxwYXJlbnQsc3BlY2ltZW5JRCBGUk9NIHN5bjIxMjIyMzQ4IHdoZXJlIHR1bW9yVHlwZT0nTWFsaWduYW50IHBlcmlwaGVyYWwgbmVydmUgc2hlYXRoIHR1bW9yJyIsICJpbmNsdWRlRW50aXR5RXRhZyI6dHJ1ZSwgImlzQ29uc2lzdGVudCI6dHJ1ZSwgIm9mZnNldCI6MCwgImxpbWl0IjoyNX0=

Can we add these to the table?

**Comment by allaway** [comment]
Added in the latest rebuild of this table: https://www.synapse.org/#!Synapse:syn21046991/tables/

Uploading the new results now.
