### ISSUE TITLE
Figure 4

### ISSUE THREAD

**Issue by jaybee84** [Sage-Bionetworks/NF_LandscapePaper_2019#84]
requesting a few updates:
1. Restrict unique LV plots to 6 LVs. 
2. Faceted LV plots with (i)-(vi) numbering  (since the main fig panels will be labeled A = heatmap, B = venn diagram, C= known LVs, D=unknown LVs etc)

Should we plan to update heatmap to show only the plotted LVs?

**Comment by sgosline** [comment]
I vote for moving the heatmap to supplemental, and also referring to the synapse table (in supplemental form)

**Comment by allaway** [comment]
works for me.
