### ISSUE TITLE
Identify latent variables that correlate with immune infiltrates

### ISSUE THREAD

**Issue by sgosline** [Sage-Bionetworks/NF_LandscapePaper_2019#9]
What latent variables are showing up that correlate with immune scores? Specifically can we replace the 'metaviper' proteins with LV scores per sample in [this analysis](https://github.com/Sage-Bionetworks/NF_LandscapePaper_2019/blob/master/results/03-DeconvMetaviperCor.Rmd)?  

Conversely, are there unidentified variables that correlate with MV proteins?

**Comment by allaway** [comment]
Closed by #15

**Comment by allaway** [comment]
Closed by #15
